export type Key =
  | 'bold'
  | 'italic'
  | 'underline'
  | 'unorderedList'
  | 'orderedList'
  | 'quote'
  | 'leftAligned'
  | 'centerAligned'
  | 'rightAligned'
  | 'link'
  | 'warning'
  | 'code'
  | 'media'
  | 'checkbox'
  | 'table'
  | 'delimiter';