"use client";
import React from "react";
import Image from "next/image";
import styles from "./NotFound.module.css";

const NotFound: React.FC = () => {
  return (<div className={styles.container}>
    <div className={styles.background}>
      <div className={styles.content}>
        <h1 className={styles.status}>404</h1>
        <h2>Ooops, this page doesn&lsquo;t exist. <br />Must have gotten lost somewhere in space.</h2>
        <a href="./"><button>Back to Earth</button></a>
      </div>
      <Image className={styles.astronaut} src="/images/404/Astronaut.png" alt="A picture of an astronaut in a white uniform with an american flag, generated by AI." height={500} width={500}/>
      <Image className={styles.meteor} src="/images/404/Meteor.png" alt="A picture of an meteor with fire under it, generated by AI." height={500} width={500}/>
      <Image className={styles.iss} src="/images/404/International Space Station.png" alt="A picture of the international space station, generated by AI." height={900} width={900}/>
      <Image className={styles.saturn} src="/images/404/Saturn.png" alt="A picture of an saturn, generated by AI." height={500} width={500}/>
    </div>
  </div>);
};

export default NotFound;
